baseURL = "https://intheshade.mayday44.xyz/"
defaultContentLanguage = "zh-cn"
languageCode = "zh-cn"
title = "In The Shade"
theme = "hugo-theme-dream"

enableRobotsTXT = false

[params]
  subtitle = "密会"
  enableComments = true
  enableSearch = true
  enableRSS = false
  enableGoogleAnalytics = false


  showSummaryCoverInPost = true
  imageZoomableInPost = true
  darkMode = true

  lightTheme = "emerald"
  darkTheme = "forest"

  headerTitle = "In The Shade"
  siteStartYear = 2025
  avatar = "images/avatar.jpg"

  showPrevNextPost = true
  showTableOfContents = true

[params.advanced]
customCSS = ["css/custom.css"]

# 支持中文日期
[params.experimental]
  jsDate = true
  jsDateFormat = "yyyy年MM月dd日"

# 每页显示x本漫画
[pagination]
  pagerSize = 20